'editor/resources/icons/font.svg' = ['.ttf']
'editor/resources/icons/image.svg' = ['.png', '.bmp', '.jpg', '.gif']
'editor/resources/icons/document.svg' = ['.txt']
'editor/resources/icons/audio.svg' = ['.wav', '.mp3', '.ogg', '.flac']
'editor/resources/icons/lua.svg' = ['.luau', '.lua']